// Design tokens for the redesigned (Chat / Dashboard / For my doctor) screens, converted
// from the Lovable prototype's oklch palette. Older screens still use constants/colors.ts.
export const UI = {
  colors: {
    background: '#fef9f4',
    foreground: '#241c17',
    card: '#fffefd',
    primary: '#f6b0a6',
    primaryStrong: '#8f3830',
    primaryForeground: '#251614',
    secondary: '#d8f2e6',
    secondaryForeground: '#05281d',
    muted: '#f5efe9',
    mutedForeground: '#554b44',
    accent: '#d5f0ff',
    accentForeground: '#032839',
    destructive: '#be3029',
    border: '#dad1c7',
    success: '#1f4d2d',
    successSoft: '#def6e3',
    coralSoft: '#ffe6e2',
    blueSoft: '#dbf3ff',
    bleeding: '#8a000e',
    bleedingLight: '#a92229',
    bleedingDark: '#6f0006',
    white: '#ffffff',
  },
  font: {
    display: 'InstrumentSerif_400Regular',
    body: 'WorkSans_400Regular',
    semibold: 'WorkSans_600SemiBold',
    bold: 'WorkSans_700Bold',
  },
  size: {
    body: 18,
    small: 16,
    tiny: 14,
    h3: 20,
    h2: 24,
    display: 38,
  },
  radius: 8,
  minTap: 56,
  gutter: 20,
} as const;
