services:
  - type: web
    name: atossa-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: GOOGLE_WEB_CLIENT_ID
        value: 803449042490-s817ucvtsahd80stfng3isvv0efta0ku.apps.googleusercontent.com
