"""initial schema

Revision ID: 56d2929adde1
Revises: 
Create Date: 2026-06-04 15:57:48.115698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d2929adde1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_to_contacts', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_user_id'), 'alert_logs', ['user_id'], unique=False)
    op.create_table('connected_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('viewer_user_id', sa.String(), nullable=True),
    sa.Column('invite_email', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('can_view_cycle', sa.Boolean(), nullable=False),
    sa.Column('can_view_symptoms', sa.Boolean(), nullable=False),
    sa.Column('can_view_metrics', sa.Boolean(), nullable=False),
    sa.Column('can_receive_alerts', sa.Boolean(), nullable=False),
    sa.Column('invite_token', sa.String(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_connected_accounts_owner_user_id'), 'connected_accounts', ['owner_user_id'], unique=False)
    op.create_table('cycle_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=False),
    sa.Column('period_end', sa.String(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('period_length', sa.Integer(), nullable=True),
    sa.Column('flow_intensity', sa.String(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_logs_user_id'), 'cycle_logs', ['user_id'], unique=False)
    op.create_table('cycle_predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_period_start', sa.String(), nullable=True),
    sa.Column('next_period_end', sa.String(), nullable=True),
    sa.Column('next_ovulation', sa.String(), nullable=True),
    sa.Column('fertile_window_start', sa.String(), nullable=True),
    sa.Column('fertile_window_end', sa.String(), nullable=True),
    sa.Column('predicted_cycle_length', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('method_used', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_predictions_user_id'), 'cycle_predictions', ['user_id'], unique=True)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('notify_on_heavy_bleeding', sa.Boolean(), nullable=False),
    sa.Column('notify_on_fainting', sa.Boolean(), nullable=False),
    sa.Column('notify_on_missed_period', sa.Boolean(), nullable=False),
    sa.Column('call_911_after_no_response', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metrics_user_id'), 'health_metrics', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('average_cycle_length', sa.Integer(), nullable=False),
    sa.Column('average_period_length', sa.Integer(), nullable=False),
    sa.Column('cycle_regularity', sa.String(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('logged_date', sa.String(), nullable=False),
    sa.Column('logged_time', sa.String(), nullable=False),
    sa.Column('symptom_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('custom_label', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_logs_user_id'), 'symptom_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symptom_logs_user_id'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_health_metrics_user_id'), table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_cycle_predictions_user_id'), table_name='cycle_predictions')
    op.drop_table('cycle_predictions')
    op.drop_index(op.f('ix_cycle_logs_user_id'), table_name='cycle_logs')
    op.drop_table('cycle_logs')
    op.drop_index(op.f('ix_connected_accounts_owner_user_id'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index(op.f('ix_alert_logs_user_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    # ### end Alembic commands ###
