"""add profile foreign key

Revision ID: a0aae4dc18c9
Revises: 56d2929adde1
Create Date: 2026-06-04 16:01:06.584325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0aae4dc18c9'
down_revision: Union[str, None] = '56d2929adde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'profiles', 'users', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    # ### end Alembic commands ###
